### ISSUE TITLE
Multipledatepicker에서 date받아와서 표시하는 과정

### ISSUE THREAD

**Issue by WonjeongPark** [WonjeongPark/howto#1]
1. TrainerProfileForm.jsx에서 
다른 input들은 ProfileChange 함수를 사용하고
date는 Multipledatepicker사용으로 인해 dateChange함수를 사용하게 된 부분에 대해서
refactoring으로 모두 profileChange함수를 사용하도록 바꿔보려고 했는데요.

Multipledatepicker에서 attribute를 (name) 찾아내는 방법을 모르겠고,
array로 받아지는 dates를 ProfileChange함수에서처럼
[e.target.name]: e.target.value 이 방법으로 name과 value로 setState 할수 있는지
아직 모르겠어요. 체크해놓고 더 찾아볼게요.

2. TrainerProfileForm.jsx에서 
dataChange에서 선택된 dates가 console에서 한박자씩 뒤늦게 보였던 부분은
Lifecycle관련해서 setState 시점이 profileSubmit함수 실행타이밍과 달라 그런 것같아
submit을 하면 알맞은 타이밍에 console에 보이는 것 보고 넘어갔습니다.

3. TrainerProfileForm.jsx에서
Multipledatepicker로 dates받아와서 dateChange함수 부분에서
toLacaleString을 이용하여 date 형식을 바꾸고 console로 확인하니
 ["2", "0", "1", "9", "년", " ", "4", "월", " ", "2", "5", "일", " ", "목", "요", "일", ",", "2", "0", "1", "9", "년", " ", "4", "월", " ", "2", "6", "일", " ", "금", "요", "일"]  이런 형식으로 되어서요.

TrainerProfile.jsx에서
 join하고 "," ->split하고 .map을 이용해서 줄바꿈하여 표시해봤습니다.
원하는 화면은

2019년 4월 29일 월요일
2019년 4월 30일 화요일

이렇게 줄바꿈이 되어 출력되는 것입니다.

줄바꿈을 제외하고 join을 하지 않아도 화면에 보이는건 똑같지만
나중에 저 data를 활용할 때 위의 예시처럼 "이","렇","게" 나눠져있는게
더 활용성이 떨어질 것 같은 판단으로 해보았는데
위의 과정이 불필요한지,, join, split, map 를 사용하지 않고
"이","렇","게","나","눠","진", data가 
 
2019년 4월 29일 월요일,2019년 4월 30일 화요일

이렇게 출력되는 화면에서 줄바꿈하는 다른 방법을 더 찾아야하는지 궁금합니다.

간단하게 input에서 받는 data를 출력하는 과정인데
date array가 들어갔다고 며칠이 걸린건지..
하는 과정동안은 답답하고 그랬는데 풀려서 속시원해졌어요.
물론 더 고쳐나가야하지만요.
그래서 Issue 올리는 시간이 늦어졌어요. 
다음에는 더 일찍 올려보겠습니다.

**Comment by jongfeel** [comment]
크게 리뷰해볼 부분이

1. Multipledatepicker에서 attribute 속성 부여하는 방법이 있는지
2. dates, 즉 date array 객체에 대한 string formatting 알아보기
겠네요.

집중적으로 리뷰 진행해 봐요.

**Comment by jongfeel** [comment]
오늘 리뷰하고 기록 남기신걸 잘 보시면 될 거 같아요. 

https://github.com/WonjeongPark/whatIThink/pull/13
