### ISSUE TITLE
서버 작업 완료 (?)

### ISSUE THREAD

**Issue by WonjeongPark** [WonjeongPark/howto#11]
우선 참고하던 게시글 보고 서버만들고 데이터베이스 연결까지 완료한 상황입니다.
중간에 버전업된 부분이나 조금씩 다른 부분이 있어서 많이 막히면서 온 것 같아요!
총 정리 겸 다시한번 처음부터 해온 과정 리뷰해보고 (★)
게시글에 있던 예제로 db를 만든 상황이라 이제 howto에 해당하는 프로필 db를 만들어야 할 것 같습니다.

**Comment by WonjeongPark** [comment]
다시 보니 일단 test에서 'before'사용에 에러가 있어서 첫번째 테스트는 실행이 안된 것 같아서 다시 봐야 할 것 같고,
아직 조금 더 찾아봐야 할 부분이 있는 것 같아서 완료아직 아닙니다!

**Comment by WonjeongPark** [comment]
작성해놓은 test는 두개다 통과했으나 before 부분 오류뜨는건 아직 찾는 중입니다!
이제 howto db에 적용시키는 방법 찾아보려고 합니다.

**Comment by jongfeel** [comment]
미팅 시간에도 얘기한 거지만 글을 달아 드리면
unit test에 대해 좋은 인식이 생기셨다면 쭉 진행해 보시는 걸 권장드립니다.
unit test의 필요성에 대해 인지하고 하는 것과 안하고 그냥 좋다니까 하는 것과는 아주 다른 결과를 낳게 됩니다.
