### ISSUE TITLE
서버 구동 후 홈화면

### ISSUE THREAD

**Issue by WonjeongPark** [WonjeongPark/howto#12]
우선 서버까지 잘 돌아가서 npm start하면
비어있는 users 배열이 
[]
이렇게 뜨는데요.

npm start하면 
제가 디비랑 서버하기전에 해놓았던 홈페이지가 뜨게하는 방법을 정확히 모르겠어요.

1. package.json에 scripts, start 부분을 바꿔도 실행이 안되고
지금 start : node bin/www가 서버를 구동시키는 거니 바꾸는건 아닌 것 같다는 판단이 들었어요.

2.
지금 화면에 뜨는 빈 배열이
/app.js 에서
app.use('/', require('./api/users/index')); 이부분이니까
여기서 불러 올 수 있지 않을 까라는 생각이 들어서요.

찾아보니 app.get으로 동적파일, 정적파일 불러오는 부분이 있어서
이미지 같은 동적화면 방법이 아닌
정적화면 불러오는 방법으로
app.get('*', function (request, response){
     response.sendFile(path.resolve(__dirname, 'src', 'index.js'))
   }) 로 시도해봤는데
src/index.js에서
import React from react 에서 React가 Incorrect하다고 뜨네요.
이 오류에 대해서도 찾아봤는데 npm update도 해결방안이 아니네요.

https://velopert.com/2037
계속 찾아보니 webpack, babel 이야기가 많이 나오는데
node_modules/react-scripts 에 설치되어 있으니
npm run eject를 실행해서 react-scripts를 삭제하고
package.json에 프로젝트로 생성하려고 해도

'react-scripts'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.

라는 오류로 막히네요.

제가 서버는 서버대로 돌아가는 것과
view가 보이는 각각의 흐름은 어느정도 안다고 생각하는데
둘의 연결고리 부분을 잘 이해못하는 것같아요.

이리저리 검색어 바꿔가며 검색하고 코드 계속 보고 노력중입니다 ㅜㅜ

**Comment by jongfeel** [comment]
구체적인 문제점을 잘 적어주셨네요.

리뷰해 보면 좋을 것 같습니다.
