### ISSUE TITLE
현재상황

### ISSUE THREAD

**Issue by WonjeongPark** [WonjeongPark/howto#13]
1. 'react-scripts'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다 - 해결 못함

서버 구축하면서  컴퓨터-마우스오른쪽-속성-고급시스템설정-환경변수-시스템변수 PATH를
nodejs로 수정한 적이 있어서 관련해서 검색해보고 
C:\Program Files\nodejs; 를
C:\Users\LG\howto; C:\Program Files\nodejs; 와
C:\Users\LG\AppData\Roaming\npm; C:\Program Files\nodejs; 에서 수정해봤는데도 오류는 그대로.

2. create-react-app의 경우 webpack등의 설치가 필요 없는 경우(?)가 version2이고
다시보니 저는 v1이라서요 검색해서 찾아보고 설치해봤습니다.
(node-module폴더에 react-scripts에 v2와같이 webpack내용이 있어서 저도 v2이라 착각했어요)

https://poiemaweb.com/es6-babel-webpack-2
예제만들어서 잘 돌아가길래 entry : 'src/index.js' 로 해보니 

ERROR in ./src/index.js 13:8
Module parse failed: Unexpected token (13:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| let render = () => {
|     ReactDOM.render(
>         <BrowserRouter>
|         <App />
|         </BrowserRouter>,

이런 에러가 떴구요. 에러에 뜬 사이트
https://webpack.js.org/concepts/#loaders 를 보니
javascript & json만 된다고 하길래요.

webpack loader react 검색하다가

https://velog.io/@padakim/Webpack4-for-React-%EB%A6%AC%EC%95%A1%ED%8A%B8%EB%A5%BC-%EC%9C%84%ED%95%9C-%EC%9B%B9%ED%8C%A94-1-

게시글 적용해보려니까 오류로 안되는 상황이예요.
그런데 위 게시글은 npm install webpack-dev-server 을 따로 하긴 하네요.

우선은 현 상황은 이렇구요 ㅜㅜ 가능하면 오늘밤이나 낼 오전에 좀더 해보고
다시 이슈 올려볼게요.
조금 더 찾아보면 될 것 같기도 하다가도
전혀 다른곳에서 헤메고 있는건가 싶기도하네요.

**Comment by jongfeel** [comment]
열심히 진행하고 계시는 군요!
저도 오늘 쯤에 한번 확인해 볼께요

**Comment by jongfeel** [comment]
아무래도 front쪽에 webpack build 할 때 index.html을 만들고 시작하는게 좋을 거 같아요.
이것도 한번 시도해 보고 진행해 보세요.

**Comment by WonjeongPark** [comment]
public/ index.html을 활용해서 시도해보긴 했는데
다시 그쪽으로 찬찬히 해보겠습니다.
