### ISSUE TITLE
React.js + Node.js server

### ISSUE THREAD

**Issue by jongfeel** [WonjeongPark/howto#15]
이 환경이 구동될 수 있는 방법 찾아서 정리

**Comment by WonjeongPark** [comment]
https://medium.com/@maison.moa/setting-up-an-express-backend-server-for-create-react-app-bc7620b20a61

여기서 하는 방법대로 해서 사이트에 나온 것 처럼 결과가 나왔어요.

저는 'howto' root 안에 서버 www 를 만들었는데

사이트에서는 예를 들어
root directory인 howto3안에서 create-reacte-app client를 해서요.

howto 에 npm init으로 생성된 package.json을 설치, 서버파일 server.js 생성하고 코딩 간단하게 하고
client의 package.json의 proxy설정으로 localhost:5000에서 express가 연결된거 확인하고
client에서 npm start하면 미리 설정한 express 연결되면 나타는 문장이 뜨네요. 

집에가서 디비랑 연결하는 부분 해보고..
howto에 적용해볼게요.

저 사이트에서는 의외로 너무 간단하게 해서..
제가 애초에 서버를 생성한 위치가 잘못된건 아닌가 하는 생각이 드네요.

제가 다시 해보고 월요일에 이슈 다시 올리겠습니다.

**Comment by WonjeongPark** [comment]
하루 늦었네요. 우선은 저 방법으로 mysql에 있는 array가져오는건 가능해요.
처음부터 찾아보면서 componentDidMount에 callback함수 이용해서 가져 오는 방법을 보긴 봤었는데
다른 문제에 집중하느라 잊고있었는데요. 위에 게시글 참고해서 하니까 되더라구요.
일단은 속이시원해요 (?) 
아직은 App.js 안에서만 불러오기해봤는데 console.log로 찍어보니 잘 나오더라구요.
다만 return해서 값을 보이게하는 부분에서 막혔는데 이거는 서버관련 문제가 아니라
객체관련한 문제라서 넘어야할 산(?)이기에 찾아보고 해결하려고 해요.
그렇게하고 howto에 제대로 적용 해보겠습니다.

**Comment by WonjeongPark** [comment]
{"data":[{"id":1,"name":"박원정","gym":"스포애니문정점","gender":"여성","career":"1년~2년","dates":"2019-02-14T12:34:56.000Z","bodypart":"목","playerSource":"http://media.w3.org/2010/05/sintel/trailer.mp4","count":10,"setNum":3,"createdAt":"2019-06-30T15:54:09.000Z","updatedAt":"2019-06-30T15:54:09.000Z"}]}
