### ISSUE TITLE
Form에서 hook을 적용하는 것, 동영상url받아와서 게시하는 것

### ISSUE THREAD

**Issue by WonjeongPark** [WonjeongPark/howto#2]
1. Form에서 hook을 이용하여 count 함수를 적용시켜보려고 했으나 (Counter.jsx)
등록버튼을 누르지 않아도 카운트함수가 변하면(ex. +1버튼 클릭)
바로 submit 되는 현상이 발생되어서
이렇게저렇게 해보다가 일단은 select input으로 바꿔놓았어요.
적용가능한건지 더 찾아보고, 시도할 예정입니다.

2. Form에서 동영상 url을 등록하면 TrainerVideo에 나오게끔 시도해보려고
일단 Video-React라는 걸 다운받아서 적용해보고 있는데
https://video-react.js.org/components/player/

// import "../node_modules/video-react/dist/video-react.css";
사이트에서 권장하는 이부분의 오류가 왜 일어나는지 모르겠고

그게 동영상크기 조절부분이랑 관련있는지(stackoverflow에 비슷한 사례가 있는데
그중에 글 하나가 저 부분을 언급해서요)
동영상크기조절이 안되서 계속 찾아보고 있는 중입니다.
글을쓰다보니
그냥 단순하게 (?) input text로 받아서 구현하는 방법이 있는지도 찾아봐야할 것 같아요.

**Comment by jongfeel** [comment]
1. 
Form tag의 경우는 button type이 지정되어야 합니다.
type을 정해주지 않으면 submit으로 동작할 거에요.

<button type="button"></button>

요렇게 해보세요

2. import의 경로를 다시 잘 설정해 보세요. 바로 상위 폴더가 node_modules 폴더가 아니에요
