### ISSUE TITLE
이번주 Issue 정리

### ISSUE THREAD

**Issue by WonjeongPark** [WonjeongPark/howto#25]
1. mysql과 dates array.
찾아보니 mysql에 dates로 array를 저장할 수 없어서 어떤 방식으로 정리할지 고민 중입니다.

우선은 dates가 `날짜, 날짜, 날짜, .. ` 이런식으로 ','로 구분되는 점을 이용해서
저장할 때 문자열로 저장, 불러올 때 ','를 기준으로 dates array로 변환하는 방법을 사용하려고
mysql에 dates 형식이 string으로 되어있어요.
하지만 막상 howto 일부를 불러와서 보니 위의 방식이 맞는 방식인가 하는 생각이 들어서요.

완벽하게 파악하지는 못했지만 찾아봤을 때 dates 테이블을 만들어서 선택된 날짜의 수만큼 하나씩 테이블에 저장하는 방법도 쓰는 것 같은데 그저 표시만 해주면 되는 데이터를 너무 복잡하게 처리하는건 아닐까? 하는 생각이 들어서 고민중입니다. 미팅 때까지 더 고민해보겠습니다.

2. 서버에서 불러오는 데이터의 형태.
시간이 꽤(?)흘렀지만 저번 미팅때 말로만 설명드렸던 그 부분입니다.

src/App.js에서 콜백함수를 통해 디비의 데이터를 불러오는 과정에서
지금 디비에 2개의 profile 이 저장되어있는데요.
users[0], users[1]다 잘 불러와지는데
users[0].name은 오류없이 잘 불러와지지만
users[1].name은 오류가 뜨더라구요. name이 undefinded 되었다면서..

디비에서 불러와서 setState하는 과정에서 제가 놓치는 부분이 있는 것 같은데
정확히 파악은 못해서 더 찾아보고 있습니다.

3. 현재 howto 일부분을 가져와서 branch 에서 작업중인 상황을 먼저 설명드릴게요.
featureJ 브랜치에서 서버에 연결된 프론트 부분은 client 폴더에 다 포함되어있구요.

mysql에서 데이터를 불러오는 콜백함수를 테스트 한 파일은 src/App.js 입니다.
howto부분을 가져와서 예전에 만들어 놓았던 home -> ProfileDashboard 로 접속되어서
profile list가 보이는 부분은 src/components/App.js 입니다.

howto에서 profile 부분만 가져와서 화면에 보이도록 만들었구요.
자잘한 부분들 좀 손보고 profile을 생성하고 삭제하는 부분을
디비와 연결하는 부분은 찾아보고 시도할 예정입니다.
위의 dates 부분을 잘 결정하고나서 도전해봐야할 사항이라
아직 실행 전입니다.

+ 저번 이슈로 써주신 부분은 뭔가 거창한 것이 아니라(?) 미팅때도 말씀드릴 수 있지만..!

npm install ~하거나 무언가 수행할 때 npm audit fix가 필요하다며 뜨는 부분과
메일로 One of your dependencies has a security vulnerability라고 계속 오는 부분 찾아보다가
깃허브에서 자동으로 제가 설치한 npm들의 update부분? 들을 pull request부분으로 받아 보는 기능이 생겼다고해서 시도해본 것입니다. ㅎㅎ

**Comment by jongfeel** [comment]
1. 이건 단호하게 말씀 드릴 수 있는데 date를 string type으로 하면 매우 피곤해집니다.
솔직히 이렇게 쓴다면 "저는 DB에 D도 모르는 사람입니다" 라고 광고하는 꼴이라서요
꼭 datetime 형태로 진행하셔야 합니다.

2. 디버깅을 조금 해보면 답을 금방 찾을 수 있을 것도 같습니다.
예전에 제가 디버깅을 하는 방법과 과정에 대해 얘기해 드렸고 실제 코딩하면서 알려 주기 까지 했으니까요. 차근 차근 디버깅 과정을 밟아가며 논리의 검증을 해보시면 쉽게 풀리게 되어 있습니다.
정 안되면 제가 또 봐드리죠.

3. 음 이건 Unit test를 좀 해보는게 좋을 것 같네요. unit test도 좀 거창한데 테스트용 CRUD  페이지 정도를 만들어 두시면 편할거에요. 매번 현재 만들어진 사이트에서 db 연결하고 디버깅 하고 하는 게 불안하다면 테스트 페이지 만드는 걸 추천드립니다. 적어도 DB에 문제가 있는지 없는지에 대한 걱정 거리는 줄어들어요.

**Comment by WonjeongPark** [comment]
1. 역시 그렇죠 ㅜㅜ 원래대로 datetime으로 돌려놓고 진행하겠습니다.
2. 다시 차근차근 디버깅 해볼게요.
3. 이 것도 시도해보겠습니다.
감사합니다.
