### ISSUE TITLE
현재 진행 상황

### ISSUE THREAD

**Issue by WonjeongPark** [WonjeongPark/howto#27]
완료상황
1. DB에서 users와 dates를 분리하고 join 
2. GET /users 를 통해 profileList 불러오기 ( dates도 같이 불러오기 가능)
-> mulipledatepicker에서 가져오는 date값을 db에 있는 값과 같은 형태로 변환
3. videoSection 적용하고 나오게 하기
4. stack and queue 글쓰기

>이슈 해결하고 findOne, delete, update 등 적용할 예정
featureJ 브랜치부분을 master로 pullrequest할 예정

issue**
1. POST /users 진행중입니다.
자꾸 error가 나와서 무엇이 문제인지 찾는 중입니다.
1) user.controller.js 에서 *create 부분* 콘솔에서 Num의 값만 안찍힘 (순서, 이름 다 상관X)
1-2) 혹은 GET과 반대로 dates array -> dates table의 한 인자로 넣는 방법이 잘못된것인지
2) TrainerProfileForm.jsx에서 fetch부분의 오류인지

찾아보는 중입니다.

**Comment by jongfeel** [comment]
문제가 되는 부분들을 오늘 리뷰해 보면 좋겠네요.
