### ISSUE TITLE
로그인 기능 추가, 회원 분리, 포트폴리오작성

### ISSUE THREAD

**Issue by WonjeongPark** [WonjeongPark/howto#29]
9월부터 서류넣기를 시작하려고 포트폴리오쓰고 howto 디자인에 시간을 많이 할애했어요.
혹 가능하시면 한번 읽어봐주세요.

그 부분이 어느정도 마무리 되고나서 저번에 말씀해주셨던 것 생각해보았어요.
Howto 사이트를 더 만들 것인지, 어느정도 만들 것인지 날짜를 정하는 것도 좋을 것 같다고 하신 부분이요.

제 생각은
1.  우선 로그인 부분을 추가하고
2.  트레이너와 수강생의 로그인, 후 화면(현재 TrainerList), 회원가입 부분 등을 분리해서
애초에 처음 생각하던데로 중개사이트 역할을 할 수 있게 하려고 합니다.

현재 node의 passport라는 미들웨어로 로그인 기능을 구현 할 수 있을까 하여 찾아보고 있어요.
아마 멘토링시간 전까지는 찾아보고 적용해보고 할 것 같아요.
혹시몰라서 브랜치 분리하여 적용시키고 나중에 머지하려고 계획중입니다.

4. 회원가입부분은 제일 처음 부분에 트레이너인지 수강생인지 선택하는 부분을 통해서
각자 맞는 form화면을 띄우려고 합니다.
그래서 현재 users 테이블에 loginID, loginPW부분 행이 추가되었어요.

db에 저장하는 과정에서 현재 저장된 users처럼 따로 분리하여 trainers와 같은 테이블을 만들어야하는지 고민입니다.

지금 제 생각은
1)같은 users 테이블에 저장하되 trainer인지 아닌지 구별할 수 있는 행을 삽입해서
특정 값이 들어있으면 트레이너, 없으면 수강생으로 구분하여
(예를 들어 trainer행에 "trainer"가 들어있으면 트레이너, null이거나 "users"가 들어있으면 수강생)
불러오는 방법이 가능하다고 생각합니다.
2)혹은 users테이블과 별개로 trainer테이블을 만들고 각각의 loginId와 logingPW가 같이 저장되는 테이블과 1:1관계로 연결된 db로 구성해야하는 것인지 고민이예요.
usersTable --(1:1)-->> loginInfo <<--(1:1)--trainerTable

아마 passport적용하면서 또 이슈가 발생할 것 같습니다. 우선은 잘 찾아보고 적용하도록 노력하겠습니다.

**Comment by WonjeongPark** [comment]
4. -> 3. 입니다.

**Comment by jongfeel** [comment]
@WonjeongPark 

우선 user와 trainer가 각각 데이터가 어떻게 다른지 정리해 보고 문서를 만들어 보시면 좋을 거 같고 
그걸 토대로 DB에 table을 어떻게 만들지 생각해 보면 좋습니다.

준비해오신 부분을 리뷰해 보면 좋을거 같네요.
