### ISSUE TITLE
Passport, 코딩테스트, 면접

### ISSUE THREAD

**Issue by WonjeongPark** [WonjeongPark/howto#31]
현재상황 -
1. howtoLogin브랜치에서 DB를 trainers<<--(1:1)--users--(1:1)-->> trainees로 나누어 다시 만들었고 controller로 다시 손봐서 현재 trainers,trainees 두 개의 Form 모두 db에 데이터 넣기가 가능합니다.
trainer Form, trainee Form 에 겹치는 users부분을 따로 빼서 리팩토링해야하는지 고민중입니다.
우선은 로그인 후에 자격에 따라 Trainer-> TraineeList, Trainee -> TrainerList 화면으로 라우팅하려고 passport적용으로 넘어갔어요.

2. passport 적용중이고 아직 CANNOT POST /LOGIN 에러가 뜨지만 다시 찬찬히 보고 해결할 예정입니다. (3번의 이유로 아직 제대로 보지 못했어요) 완성하면 게시판,좋아요 기능 스토리보드 작성으로 넘어갈 예정입니다.

3. 코딩테스트 및 면접
코딩테스트가 몇 개 잡혔는데요. 알고리즘 푸는 것에 아직은 익숙치 않아서 엄청난(?) 기대를 하지 않지만 그래도 테스트니까.. 줄어든 알고리즘 공부분량을 조금 늘리려고 합니다.

**Comment by jongfeel** [comment]
@WonjeongPark 

제 생각에는 면접 준비가 제일 급할 것으로 예상되는데요? ㅎㅎ

이번에도 리뷰할 거리를 얘기해 주셔서 감사합니다.

그런데 제가 치과 치료를 하는 중이라 말을 많이 못할거 같아요. 당분간 짧게 진행해야 할 거 같습니다.
