### ISSUE TITLE
callback함수 적용관련

### ISSUE THREAD

**Issue by WonjeongPark** [WonjeongPark/howto#6]
Counter.jsx에서
count의 +1버튼에 적용한 increment 함수에서 부모컴포넌트로 값을 보내는 과정
Form에서 확인해보면 countname은 잘 넘어가는데
countvalue 즉 버튼으로 바뀌는 value가 한박자씩 늦게 넘어가는 현상이 있는데요.
버튼을 눌러서 callback함수가 호출되고나서 setCount가 +1되는 것 같아요.
이리저리 확인해보고 검색해보고 있는데 

lifecycle로 해결해야하는건가 싶어서 찾아보는 중입니다.
이쪽으로 찾아서 해결하는게 옳은 방향일까요?

**Comment by jongfeel** [comment]
코드 리뷰를 해본 결과 코드 로직을 그렇게 짜신 거 같아요

function increment(){
      setCount(count + 1)
      countvalue = count
      onChangeCount(countname, countvalue)
    };

increment를 잘 분석해 보죠.
count = 10 이라면
setCount(count + 1) => render가 끝나면 count = 11이 될겁니다.
countvalue = count; => count=10이니까 countvalue=10 이겠죠?
onChangeCount(countname, countvalue) => 이걸 그대로 넘겨주면 10이 넘어갑니다.
즉, +1을 안한 값을 넘겨주는 거에요.

그래서
onChangeCount(countname, countvalue + 1)
요렇게 하면 됩니다.
