### ISSUE TITLE
특이사항 아직 없음.

### ISSUE THREAD

**Issue by WonjeongPark** [WonjeongPark/howto#8]
http://webframeworks.kr/tutorials/nodejs/api-server-by-nodejs-01/
이 게시물 시리즈로 참고해서,
헷갈리는 부분은 구글에서 찾아 가면서 따라가는 중입니다.
지금 세번째 끝부분에서 네번째로 넘어 가고있고요.
중간중간 이해못해서 못따라가거나 오류가 난 경우가 있었는데
찾아보고 이것저것 보고 했더니 지금 다 따라온 상태예요. 

다행히 게시물이 단계별로 잘 설명되어있어서 읽고 또 읽으면서 따라가는 중입니다.

**Comment by jongfeel** [comment]
node 공부를 열심히 하고 계시는 군요.

오늘은 node 얘기를 좀 해볼까요?

알고 계신 걸  저와 얘기해 보면 좋은 시간이 될 거 같아요.
